name: Updated Blog Posts 
on:
  schedule: # Run workflow automatically
    - cron: '0 * * * *' # Runs every day, at 1300, to avoid spam in commits
  workflow_dispatch: # Run workflow manually (without waiting for the cron to be called), through the Github Actions Workflow page directly
jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          comment_tag_name: TECH
          commit_message: "#${{ github.run_number }} Updated tech articles"
          committer_username: jrzvnn
          disable_sort: False
          max_post_count: 5
          template: $newline - [$title]($url)
          feed_list: "https://www.techmeme.com/feed.xml?x=1,https://www.wired.com/feed/rss,http://feeds.feedburner.com/androidauthority,https://www.cnet.com/rss/news/,https://appleinsider.com/rss/news/,http://feeds.feedburner.com/Techcrunch,http://www.theverge.com/rss/full.xml"
          committer_email: jrzvnngmail.com

      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          comment_tag_name: MEMES
          commit_message: "#${{ github.run_number }} New batch of memes"
          committer_username: jrzvnn
          disable_sort: False
          max_post_count: 5
          template: $newline - $randomEmoji(ğŸ˜,ğŸ‘±,ğŸ“€,ğŸš–,ğŸš…,â©,ğŸ’£,ğŸ‘‰,6ï¸âƒ£,ğŸš¯) [$title]($url)
          feed_list: "http://9gagrss.com/feed/,https://www.reddit.com/r/funny/.rss,https://www.reddit.com/r/memes/.rss"
          committer_email: jrzvnngmail.com

      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          comment_tag_name: GAME
          commit_message: "#${{ github.run_number }} Gaming updates"
          committer_username: jrzvnn
          disable_sort: False
          max_post_count: 5
          template: $newline - [$title]($url)
          feed_list: "http://feeds.feedburner.com/PSBlog,https://news.xbox.com/en-us/feed/,http://feedproxy.google.com/GameRant,http://www.polygon.com/rss/index.xml,https://kotaku.com/rss,https://www.pcgamer.com/rss/,https://blog.playstation.com/feed/"
          committer_email: jrzvnngmail.com
